In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_excel('Online_Retail.xls')

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [16]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice               int64
CustomerID              int64
Country                object
dtype: object

In [15]:
df.isna().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64

In [13]:
df['CustomerID'].fillna(0, inplace=True)

In [14]:
df['UnitPrice'] = df['UnitPrice'].astype('int64')
df['CustomerID'] = df['CustomerID'].astype('int64')

In [18]:
df['Description'].unique()

array(['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN',
       'CREAM CUPID HEARTS COAT HANGER', ..., 'lost',
       'CREAM HANGING HEART T-LIGHT HOLDER',
       'PAPER CRAFT , LITTLE BIRDIE'], dtype=object)

In [20]:
df['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [24]:
country_dialing_code_map = {
    'United Kingdom': '44',
    'France': '33',
    'Australia': '61',
    'Netherlands': '31',
    'Germany': '49',
    'Norway': '47',
    'EIRE': '353',  # Ireland
    'Switzerland': '41',
    'Spain': '34',
    'Poland': '48',
    'Portugal': '351',
    'Italy': '39',
    'Belgium': '32',
    'Lithuania': '370',
    'Japan': '81',
    'Iceland': '354',
    'Channel Islands': '44',  # Uses UK's code
    'Denmark': '45',
    'Cyprus': '357',
    'Sweden': '46',
    'Austria': '43',
    'Israel': '972',
    'Finland': '358',
    'Bahrain': '973',
    'Greece': '30',
    'Hong Kong': '852',
    'Singapore': '65',
    'Lebanon': '961',
    'United Arab Emirates': '971',
    'Saudi Arabia': '966',
    'Czech Republic': '420',
    'Canada': '1',
    'USA': '1',
    'Brazil': '55',
    'Malta': '356',
    'European Community': '388',  # Note: Not a real dialing code anymore; placeholder
    'Unspecified': None,
    'RSA': '27'  # South Africa
}

In [27]:
df['Country_Code'] = df['Country'].map(country_dialing_code_map)

In [29]:
df.drop('Country', axis = 1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country_Code
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2,17850,44
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3,17850,44
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2,17850,44
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3,17850,44
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3,17850,44
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0,12680,33
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2,12680,33
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4,12680,33
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4,12680,33
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4,12680,33

In [34]:
# Step 1: Define the ASCII sum function
def ascii_sum(code):
    return sum(ord(char) for char in str(code))

# Step 2: Apply it to the 'StockCode' column
df['StockCode_ASCII'] = df['StockCode'].astype(str).apply(ascii_sum)

In [37]:
df = df.drop('StockCode', axis = 1)

In [39]:
df=df.drop('Country', axis = 1)

In [40]:
df

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country_Code,StockCode_ASCII
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2,17850,44,324
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3,17850,44,256
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2,17850,44,328
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3,17850,44,334
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3,17850,44,332
...,...,...,...,...,...,...,...,...
541904,581587,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0,12680,33,254
541905,581587,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2,12680,33,270
541906,581587,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4,12680,33,256
541907,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4,12680,33,257
541908,581587,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4,12680,33,256

In [42]:
df['InvoiceDate'].unique()

<DatetimeArray>
['2010-12-01 08:26:00', '2010-12-01 08:28:00', '2010-12-01 08:34:00',
 '2010-12-01 08:35:00', '2010-12-01 08:45:00', '2010-12-01 09:00:00',
 '2010-12-01 09:01:00', '2010-12-01 09:02:00', '2010-12-01 09:09:00',
 '2010-12-01 09:32:00',
 ...
 '2011-12-09 12:09:00', '2011-12-09 12:16:00', '2011-12-09 12:19:00',
 '2011-12-09 12:20:00', '2011-12-09 12:21:00', '2011-12-09 12:23:00',
 '2011-12-09 12:25:00', '2011-12-09 12:31:00', '2011-12-09 12:49:00',
 '2011-12-09 12:50:00']
Length: 23260, dtype: datetime64[ns]

In [43]:
df = df.drop('InvoiceDate', axis = 1)

In [44]:
df

,InvoiceNo,Description,Quantity,UnitPrice,CustomerID,Country_Code,StockCode_ASCII
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2,17850,44,324
1,536365,WHITE METAL LANTERN,6,3,17850,44,256
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2,17850,44,328
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,3,17850,44,334
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,3,17850,44,332
...,...,...,...,...,...,...,...
541904,581587,PACK OF 20 SPACEBOY NAPKINS,12,0,12680,33,254
541905,581587,CHILDREN'S APRON DOLLY GIRL,6,2,12680,33,270
541906,581587,CHILDRENS CUTLERY DOLLY GIRL,4,4,12680,33,256
541907,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,4,12680,33,257
541908,581587,BAKING SET 9 PIECE RETROSPOT,3,4,12680,33,256

In [45]:
df['Description'].unique()

array(['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN',
       'CREAM CUPID HEARTS COAT HANGER', ..., 'lost',
       'CREAM HANGING HEART T-LIGHT HOLDER',
       'PAPER CRAFT , LITTLE BIRDIE'], dtype=object)

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Clean or fill NaNs
df['Description'] = df['Description'].fillna('')

# Step 2: TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=100)  # You can increase or reduce this
X_tfidf = tfidf.fit_transform(df['Description'])

# Step 3: Merge into your DataFrame
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())
df = pd.concat([df.reset_index(drop=True), tfidf_df.reset_index(drop=True)], axis=1)

AttributeError: 'int' object has no attribute 'lower'